CSI: Implement Expand Volume
exoscale/exoscale-csi-driver pull request #1
Opened 2024-01-19 13:59 UTC by pierre-emmanuelJ

# Description
Add the ability to resize a Block Storage volume and expand the file-system.

## Checklist
(For exoscale contributors)

* [ ] Changelog updated (under *Unreleased* block)
* [ ] Integration tests OK

## Testing

2024-01-19 15:36 UTC, sauterp reviewed
don't forget to add an integration test please

2024-01-19 15:36 UTC, sauterp commented on driver/helpers.go
> +func getNewVolumeSize(capacityRange *csi.CapacityRange) (int64, error) {
Could you write some tests for this function? (Not integ tests just some "unit" tests to verify the logic)

2024-01-19 15:36 UTC, sauterp commented on driver/helpers.go
> +	if requiredSet && limitSet && requiredBytes == limitBytes {
I think this case is unnecessary given the next one.

2024-01-19 15:36 UTC, sauterp commented on driver/controller.go
> +	}
wouldn't it be better to do these checks before we do the resize call?
As it is now the block storage volume could get resized and then would you could get the error "volumeCapabilities not supported..." after.

2024-03-20 13:23 UTC, zifeo commented
hello @pierre-emmanuelJ, we would be interested in testing that feature. Is the PR safe enough to be tested/used?

2024-03-21 08:50 UTC, pierre-emmanuelJ commented
> hello @pierre-emmanuelJ, we would be interested in testing that feature. Is the PR safe enough to be tested/used?

Hello @zifeo 

Thanks for your interest in the Block Storage volume resize feature! 

Unfortunately, due to limitations in the current Exoscale Block Storage design, this PR currently only supports offline resizing. This means that to resize a volume, it would need to be detached from the Kubernetes node first.

While we understand this isn't ideal for a Kubernetes environment... 

Online resizing isn't currently supported by Exoscale. This PR implements the groundwork for future online resizing when Exoscale offers that functionality.

**Important Note**: This PR currently support offline volume resizing only. To resize a volume, it must be detached from the Kubernetes node, causing downtime for pods using that volume.

2024-03-21 09:10 UTC, zifeo commented
@pierre-emmanuelJ Thanks for the notice, is there a place where we can track the progress or a roadmap for online resizing?

2024-03-21 10:24 UTC, sauterp commented
@zifeo I created an issue to track the issue of online resizing, any updates will be posted there. https://github.com/exoscale/exoscale-csi-driver/issues/23

2024-04-08 10:04 UTC, sauterp approved these changes

2024-04-08 10:12 UTC, sauterp requested changes
integ-test isn't passing yet :(

2024-04-08 13:35 UTC, sauterp approved these changes

2024-04-09 07:31 UTC, arnaudgeiser approved these changes

2024-04-09 09:39 UTC, merged